### ISSUE TITLE
elasticsearch 6.8.3 won't start after OpenJDK update

### ISSUE THREAD

**Issue by djflux** [djflux/meza#24]
After the most recent OpenJDK update for RHEL/Rocky the elasticsearch version installed with meza will not start. This issue was discovered when trying a fresh meza install on Rocky 8.7. 

Here are the versions in question:

meza commit c47cec from https://github.com/djflux/meza/35.x-rhel8
rocky-release-8.7-1.2.el8.noarch
elasticsearch-6.8.23-1.noarch from https://artifacts.elastic.co/packages/6.x/yum
java-1.8.0-openjdk-1.8.0.352.b08-2.el8_7.x86_64

Here are the relevant log messages from /opt/data-meza/elasticsearch/log/meza_cluster1.log

```
[2023-01-10T15:45:41,598][ERROR][o.e.b.Bootstrap          ] [meza_node_1] Exception
java.lang.IllegalStateException: failed to load plugin class [org.elasticsearch.xpack.core.XPackPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:616) ~[elasticsearch-6.8.23.jar:6.8.23]
...
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/pki/java/cacerts" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_352]
```

Looks like a JDK policy changed the ability to read cacerts.

This elasticsearch discussion thread provides a suggested resolution:

https://discuss.elastic.co/t/elasticsearch-is-incompatible-with-new-versions-of-openjdk-from-redhat/318928/7

ACTION: automate resolution in meza ansible.

The long-term fix is to update meza to MediaWiki 1.39.x and a newer version of elasticsearch. Will open a new issue for this one.

**Comment by djflux** [comment]
Commit 6d87712 resolves this issue.
