### ISSUE TITLE
Failure in TASK [mediawiki : Verify metastore index upgraded]

### ISSUE THREAD

**Issue by djflux** [djflux/meza#28]
39.x-dev branch produces the error below when trying to verify that the CirrusSearch metastore index is upgraded.

I believe this is a result of a change in php 8.x. SemanticMediaWiki maintenance script was also barking about:

`Fatal error: Uncaught Error: SMW\Setup::initExtension(): Argument #1 ($vars) cannot be passed by reference in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php:46`

This issue even occurs with the `dev-master/4.x-dev` version of SemanticMediaWiki.

I think until SMW gets fixed up the 39.x-dev branch is going to have these types of failures when running `sudo meza deploy monolith`

Will update when more SMW repo updates occur.

```
TASK [mediawiki : Verify metastore index upgraded] *****************************
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "WIKI=demo php /opt/htdocs/mediawiki/extensions/CirrusSearch/maintenance/Metastore.php --upgrade",
    "delta": "0:00:00.259536",
    "end": "2023-01-18 16:59:29.339674",
    "rc": 255,
    "start": "2023-01-18 16:59:29.080138"
}

STDOUT:


Deprecated: Return type of SMW\SQLStore\ChangeOp\ChangeOp::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/ChangeOp/ChangeOp.php on line 97

Deprecated: Return type of SMWDataItem::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DataItem.php on line 254

Deprecated: Return type of SMW\SemanticData::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/SemanticData.php on line 900

Fatal error: Uncaught Error: SMW\Setup::initExtension(): Argument #1 ($vars) cannot be passed by reference in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php:46
Stack trace:
#0 /opt/htdocs/mediawiki/includes/registration/ExtensionRegistry.php(527): SemanticMediaWiki::initExtension(Array)
#1 /opt/htdocs/mediawiki/includes/registration/ExtensionRegistry.php(279): ExtensionRegistry->exportExtractedData(Array)
#2 /opt/htdocs/mediawiki/includes/Setup.php(278): ExtensionRegistry->loadFromQueue()
#3 /opt/htdocs/mediawiki/maintenance/doMaintenance.php(83): require_once('/opt/htdocs/med...')
#4 /opt/htdocs/mediawiki/extensions/CirrusSearch/maintenance/Metastore.php(162): require_once('/opt/htdocs/med...')
#5 {main}
  thrown in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php on line 46


MSG:

non-zero return code

```

**Comment by djflux** [comment]
This SMW pull request patch seems to resolve this error: 

https://patch-diff.githubusercontent.com/raw/SemanticMediaWiki/SemanticMediaWiki/pull/5354.patch

However a new one cropped up running this command from the CLI:

`WIKI=demo php /opt/htdocs/mediawiki/extensions/CirrusSearch/maintenance/Metastore.php --upgrade`

```
Deprecated: Return type of SMW\SQLStore\ChangeOp\ChangeOp::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/ChangeOp/ChangeOp.php on line 97

Deprecated: Return type of SMWDataItem::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DataItem.php on line 254

Deprecated: Return type of SMW\SemanticData::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/SemanticData.php on line 900

Deprecated: Return type of SMW\Options::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Options.php on line 172

Deprecated: Use of LinksUpdateConstructed hook was deprecated in MediaWiki 1.38. [Called from SMW\MediaWiki\Hooks::register in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php at line 151] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381

Deprecated: Use of PersonalUrls hook was deprecated in MediaWiki 1.39. [Called from SMW\MediaWiki\Hooks::register in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php at line 151] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381

Deprecated: Use of SkinTemplateNavigation hook was deprecated in MediaWiki 1.39. [Called from SMW\MediaWiki\Hooks::register in /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php at line 151] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381
mw_cirrus_metastore missing, creating new metastore index.
Creating metastore index... mw_cirrus_metastore_firstScanning available plugins...none
Elastica\Exception\ResponseException from line 178 of /opt/htdocs/mediawiki/vendor/ruflin/elastica/src/Transport/Http.php: request [/mw_cirrus_metastore_first/] contains unrecognized parameter: [include_type_name]

```

Maybe root cause is change to elasticsearch? More checking.

**Comment by djflux** [comment]
elasticsearch 8.x and CirrusSearch might be a large undertaking :(

https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/179
