### ISSUE TITLE
Error: Call to undefined method WikiPage::doEditContent() for SemanticMeetingMinutes

### ISSUE THREAD

**Issue by djflux** [djflux/meza#31]
During a `meza deploy monolith` the following error occurred:

```
Starting import from SemanticMeetingMinutes.

Template:Meeting changed.


STDERR:

[c71c5a517ba867c0f2b79d65] [no req]   Error: Call to undefined method WikiPage::doEditContent()
Backtrace:
from /opt/htdocs/mediawiki/extensions/PageImporter/PageImporter.class.php(112)
#0 /opt/htdocs/mediawiki/extensions/PageImporter/importPages.php(71): PageImporter->import(PageImporterImportPages, boolean)
#1 /opt/htdocs/mediawiki/maintenance/includes/MaintenanceRunner.php(309): PageImporterImportPages->execute()
#2 /opt/htdocs/mediawiki/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#3 /opt/htdocs/mediawiki/extensions/PageImporter/importPages.php(86): require_once(string)
#4 {main}


MSG:

non-zero return code
```

**Comment by djflux** [comment]
This method is being called from the `PageImporter` extension in PageImporter.class.php, line 115 in the master branch:

https://github.com/enterprisemediawiki/PageImporter/blob/master/PageImporter.class.php#L115

Looks like `WikiPage::doEditContent()` was deprecated in MW 1.32 and finally removed in 1.36 (which is why this still worked in the `rhel8-35.x` branch). See:

https://www.mediawiki.org/wiki/Release_notes/1.36

and search for `doEditContent` in the page. That page recommends using `WikiPage::doUserEditContent()` but also states that method is ALSO deprecated. [facepalm] Going to search more release notes for what method to use instead of `doUserEditContent()`

Forked PageImport and working on a pull request. Fork is here:

https://github.com/djflux/PageImporter

**Comment by djflux** [comment]
PHP Class info from MediaWiki REL1_39 recommends using `PageUpdater::saveRevision`:

https://doc.wikimedia.org/mediawiki-core/REL1_39/php/classWikiPage.html#a9aeff9c38d314ecb631af379213094dc

and has a note: 

> Note that the new method expects callers to take care of checking EDIT_MINOR against the minoredit right, and to apply the autopatrol right as appropriate.

PageUpdater info is here:

https://doc.wikimedia.org/mediawiki-core/REL1_39/php/classMediaWiki_1_1Storage_1_1PageUpdater.html#a4307f714cdc1363a3bc53d9fe6908117

Going to try to get saveRevision working in my fork. Here goes nothing :)
