### ISSUE TITLE
Special:ViewXML internal error

### ISSUE THREAD

**Issue by djflux** [djflux/meza#35]
The following error occurs when viewing Special:ViewXML on 39.x-dev. Fix it.

[Y9gHrW_AW4kOpl2mzpvuUgAAAM4] /demo/index.php?title=Special:ViewXML&requestDebug Error: Call to a member function getNamespaces() on null

Backtrace:

from /opt/htdocs/mediawiki/extensions/DataTransfer/specials/DT_ViewXML.php(136)
#0 /opt/htdocs/mediawiki/extensions/DataTransfer/specials/DT_ViewXML.php(19): DTViewXML->doSpecialViewXML(NULL)
#1 /opt/htdocs/mediawiki/includes/specialpage/SpecialPage.php(701): DTViewXML->execute(NULL)
#2 /opt/htdocs/mediawiki/includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run(NULL)
#3 /opt/htdocs/mediawiki/includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#4 /opt/htdocs/mediawiki/includes/MediaWiki.php(904): MediaWiki->performRequest()
#5 /opt/htdocs/mediawiki/includes/MediaWiki.php(562): MediaWiki->main()
#6 /opt/htdocs/mediawiki/index.php(50): MediaWiki->run()
#7 /opt/htdocs/mediawiki/index.php(46): wfIndexMain()
#8 {main}

**Comment by djflux** [comment]
The REL1_39 branch of DataTransfer resolves this issue. Commit ad8de999edad600894eb20f344b1464b70a75495 changes meza to use REL1_39.
